### ISSUE TITLE
Method for tracking models after many xvers

### ISSUE THREAD

**Issue by ivanred6** [ivanred6/geneticstyletransfer#31]
- [x] How do we classify models? 
- [x] dynamic data structure? 
- [x] for ssim mean, we need to know all of the reference points to create it (i.e. all images to be used for control)
- [x] Create Issue(s) for implementing
- [x] implement
